"""Guard the retired dashboard CSS without treating dynamic classes as unused."""

import json
from pathlib import Path
import re
import unittest


class NeoSektorCssCleanupTest(unittest.TestCase):
    def test_retired_dashboard_classes_are_absent_and_live_menu_is_preserved(self):
        root = Path(__file__).resolve().parents[1]
        retired = (
            "neosektor-shell", "neosektor-hero", "neosektor-kicker",
            "neosektor-menu", "neosektor-menu-link-secondary",
            "neosektor-overview-panel", "neosektor-overview-grid",
            "neosektor-mode-pill", "neosektor-operator-title",
        )
        pattern = re.compile(r"(?<![\w-])(?:" + "|".join(retired) + r")(?![\w-])")
        # Include shared templates, inline JS, external JS and Python-generated
        # markup; do not infer absence from one dashboard template alone.
        for source in (root / "app").rglob("*"):
            if source.suffix in {".html", ".js", ".py"}:
                self.assertIsNone(pattern.search(source.read_text(encoding="utf-8")), source)

        css = (root / "app/static/css/12-neosektor.css").read_text(encoding="utf-8")
        self.assertIsNone(pattern.search(css))
        self.assertIn(".neosektor-menu-link {", css)
        self.assertIn(".neosektor-menu-link:hover,", css)
        self.assertIn(".neosektor-menu-link:focus-visible {", css)
        self.assertIn(".neosektor-status-overflowing {", css)  # Generated by Ballmat JS.
        sequence = json.loads((root / "app/static/css/sequence.json").read_text())
        files = [item["file"] for item in sequence["stylesheets"]]
        self.assertEqual(files[12:17], [
            "12-neosektor.css", "13-shared.css", "14-neoscorpion.css",
            "15-shared.css", "16-neosektor.css",
        ])
