"""Guard the retired dashboard CSS without treating dynamic classes as unused."""

import json
from pathlib import Path
import re
import unittest


class NeoSektorCssCleanupTest(unittest.TestCase):
    def test_display_bundles_keep_page_rules_and_mobile_overrides_separate(self):
        css_root = Path(__file__).resolve().parents[1] / "app/static/css"
        driver = (css_root / "neosektor_driver_routing.css").read_text()
        discharge = (css_root / "neosektor_discharge.css").read_text()
        self.assertFalse((css_root / "neosektor_display.css").exists())
        self.assertNotIn("#sektor-discharge", driver)
        self.assertNotIn("#sektor-tv", discharge)
        self.assertNotIn("data-driver-routing", discharge)
        for css in (driver, discharge):
            self.assertEqual(css.count("@media"), 1)
            self.assertIn("@media (max-width:900px) {", css)
        self.assertLess(driver.index("#sektor-tv [data-driver-bay-name]"), driver.index("@media"))
        self.assertGreater(driver.index("html:not(#sektor-tv)"), driver.index("@media"))
        self.assertLess(discharge.index("#sektor-discharge .neosektor-discharge-row"), discharge.index("@media"))
        self.assertGreater(discharge.index("body:has(#sektor-discharge)"), discharge.index("@media"))

    def test_retired_dashboard_classes_are_absent_and_live_menu_is_preserved(self):
        root = Path(__file__).resolve().parents[1]
        retired = (
            "neosektor-shell", "neosektor-hero", "neosektor-kicker",
            "neosektor-menu", "neosektor-menu-link-secondary",
            "neosektor-overview-panel", "neosektor-overview-grid",
            "neosektor-mode-pill", "neosektor-operator-title",
        )
        pattern = re.compile(r"(?<![\w-])(?:" + "|".join(retired) + r")(?![\w-])")
        # Include shared templates, inline JS, external JS and Python-generated
        # markup; do not infer absence from one dashboard template alone.
        for source in (root / "app").rglob("*"):
            if source.suffix in {".html", ".js", ".py"}:
                self.assertIsNone(pattern.search(source.read_text(encoding="utf-8")), source)

        css = (root / "app/static/css/12-neosektor.css").read_text(encoding="utf-8")
        self.assertIsNone(pattern.search(css))
        self.assertIn(".neosektor-menu-link {", css)
        self.assertIn(".neosektor-menu-link:hover,", css)
        self.assertIn(".neosektor-menu-link:focus-visible {", css)
        self.assertIn(".neosektor-status-overflowing {", css)  # Generated by Ballmat JS.
        sequence = json.loads((root / "app/static/css/sequence.json").read_text())
        files = [item["file"] for item in sequence["stylesheets"]]
        self.assertEqual(files[12:17], [
            "12-neosektor.css", "13-shared.css", "14-neoscorpion.css",
            "15-shared.css", "16-neosektor.css",
        ])
